name: Docker Publish
on:
  release:
    types: [published]

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=evotm/trackmania
          VERSION=${GITHUB_REF#refs/tags/}
          TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:latest"
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=builddate::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=revision::$(git rev-parse --short HEAD)
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          build-args: |
            BUILD_DATE=${{ steps.prep.outputs.builddate }}
            REVISION=${{ steps.prep.outputs.revision }}